"""Добавлено поле confirmed в User

Revision ID: 005938f3dc74
Revises: 
Create Date: 2025-08-12 22:10:11.461741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005938f3dc74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
