"""Add score column to Question

Revision ID: 3543ebe8c366
Revises: f7d2ece01a8d
Create Date: 2025-08-18 10:49:10.569892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3543ebe8c366'
down_revision = 'f7d2ece01a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.alter_column('question_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('question_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('score')

    # ### end Alembic commands ###
