"""Make question_number nullable

Revision ID: 4c62459b2162
Revises: 4829373309c5
Create Date: 2025-08-16 22:21:31.127333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c62459b2162'
down_revision = '4829373309c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('question_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('question_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
