"""Add detailed question scores and essay_score to results

Revision ID: 923e3eab7a9a
Revises: 3543ebe8c366
Create Date: 2025-08-18 20:17:26.304934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923e3eab7a9a'
down_revision = '3543ebe8c366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q7', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q8', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q9', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q10', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q11', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q12', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q13', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q14', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q15', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q16', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q17', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q18', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q19', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q20', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q21', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q22', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q23', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q24', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q25', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q26', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('essay_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('essay_score')
        batch_op.drop_column('q26')
        batch_op.drop_column('q25')
        batch_op.drop_column('q24')
        batch_op.drop_column('q23')
        batch_op.drop_column('q22')
        batch_op.drop_column('q21')
        batch_op.drop_column('q20')
        batch_op.drop_column('q19')
        batch_op.drop_column('q18')
        batch_op.drop_column('q17')
        batch_op.drop_column('q16')
        batch_op.drop_column('q15')
        batch_op.drop_column('q14')
        batch_op.drop_column('q13')
        batch_op.drop_column('q12')
        batch_op.drop_column('q11')
        batch_op.drop_column('q10')
        batch_op.drop_column('q9')
        batch_op.drop_column('q8')
        batch_op.drop_column('q7')
        batch_op.drop_column('q6')
        batch_op.drop_column('q5')
        batch_op.drop_column('q4')
        batch_op.drop_column('q3')
        batch_op.drop_column('q2')
        batch_op.drop_column('q1')

    # ### end Alembic commands ###
