"""Make question_number nullable

Revision ID: f7d2ece01a8d
Revises: 4c62459b2162
Create Date: 2025-08-16 22:22:10.042721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d2ece01a8d'
down_revision = '4c62459b2162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('question_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('question_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
